 
import java.util.ArrayList;
import java.util.Scanner;
 
public class BearAndPoker {
 static ArrayList<Integer> primes;     // generated by sieve
 
 public static void main(String[] args) {
  Scanner sc=new Scanner(System.in);
  int n=sc.nextInt();
  int [] arr=new int[n];
  int last=arr[0]=update(sc.nextInt());
  boolean flag=true;
  
  for(int i=1;i<n;i++) {
   arr[i]=update(sc.nextInt());
   if(last!=arr[i]) {
    flag=false;
    break;
   } 
  }
     System.out.println((flag)?"Yes":"No");
     
 }
 
   public static int update(int n) {
    while(n%2==0)
     n/=2;
    while(n%3==0)
     n/=3;
    return n;
   }
 
}
